### ISSUE TITLE
sync time

### ISSUE THREAD

**Issue by pjritee** [CSSE1001/MyPyTutor#137]
When shutting down is there ways of speeding up the sync?
E.G. If the hashes are now cached then the hash for an answer only needs to be recomputed when that answer changes. Secondly if a "dirty set" is kept then only those files need to be checked against the server files (unless the student is logged on another machine at the same time but I guess that would be problematic anyway).

**Comment by sapi** [comment]
The slowdown is just in the server communications, unfortunately.

It still needs to request a hash from the server (that's *not* cached,
because there's always a chance that they could be logged in on another
machine, and because it's messy).  If those hashes match, then the file
won't be uploaded.

**Comment by sapi** [comment]
I increased the timeout to 10 seconds.  The code currently retries 3 times on failure, meaning about 30 seconds should be the longest possible sync.

It's not possible to reduce this any further, as the underlying issue is a network timeout.
