### ISSUE TITLE
Add an interpreter window

### ISSUE THREAD

**Issue by jgat** [CSSE1001/MyPyTutor#8]
Requirements:
- Students can run their code as with IDLE, see printed output, and then be able to run function calls.
- When the test cases are run, don't pipe stdout/stderr into the interpreter window (to avoid junk).

**Comment by pjritee** [comment]
If we add an interpreter then it probably makes sense to change the Check menu to Check/Run and then use F5 for loading into the interpreter, F6 for checking and F7 for submitting. That way the editor window would be even more like "straight IDLE".

**Comment by jgat** [comment]
If submission is now automatic for passing tests, then why do we need a
separate "submit" menu item/hotkey? (In the case where the student is
offline, they can submit when they come back online by rerunning the
"Check")

**Comment by pjritee** [comment]
True - so we could then just have F5 to load in the interpreter and move check to F6

**Comment by sapi** [comment]
I think that sounds like a good idea. 

On reflection, I think we may need some limited degree of customisation, at the very least to fix up the font issues. 

Ideally, we could handle this through environment variables. I know idle supports them, but haven't investigated in any detail. If we could set fonts through them, then that would probably be sufficient. 

If not, I'd say we could just have a mpt_shell.py script in the root directory which subclasses PyShell with the required customisations, and exec that instead of idle directly. That would be more robust, but also more fiddly.

**Comment by sapi** [comment]
Largely implemented in 720d9e1

The interpreter now respects MPT font settings, and so is readable on OS X.

It seems to behave nicely for both 'types' of problems (ie, those where the student writes functions as well as those where it's just bare `input`/`print`).

The main outstanding issue is that, as the interpreter is not actually part of the MPT app, it's not foregrounded by default (at least on OS X).  There's no OS-independent way I'm aware of of handling this, but I'm going to special-case OS X and Windows.

**Comment by sapi** [comment]
Actually, scratch that thing about special-casing.  While it can be achieved with PyWin32 and PyObjC respectively, neither are part of the standard library, so we're going to have to make do for now.

**Comment by pjritee** [comment]
I can confirm it starts up for me but how do we run the user code in the interpreter?
Somewhere else (I can't find it) I suggested we use F5 as Run Module (for consistency) and the now freed up F6 as Check and change the top-level menu to Check/Run

**Comment by sapi** [comment]
The user code is already loaded, as in idle; you can just call it.

Agreed about that change.

**Comment by pjritee** [comment]
Ah - OK - but if the user changes their code and wants to test it then it would be consistent with IDLE to press F5. I assume if I move to a new problem that code will be loaded automatically - no - just tried it.

**Comment by sapi** [comment]
Pressing F5 (or, at the moment, open interpreter) should work, provided that is pressed from MPT.

Because this is just IDLE in a subprocess, we're really limited in how we can communicate with it.  It's basically just down to killing/restarting the process, or sending signals.

Unfortunately, when IDLE is started with `-r` (read from file), I can't seem to find a signal which will cause it to reload that file.  `kill -SIGINT pid` will reset the interpreter, but it won't run the file again.  IDLE also won't re-run `$IDLESTARTUP` when interrupted, so that route is out as well.

I could reload the shell when problems are switched, but that would clear anything that's currently in there.  Thoughts?

**Comment by sapi** [comment]
Actually, I think this is doable by setting a custom signal handler in `$IDLESTARTUP`.  I've got to run off to an appointment now, but I'll give that a shot afterwards.

**Comment by pjritee** [comment]
(An aside question): In playing with the interpreter I noticed that the keybindings were not set the way I wanted (using up/down arrows for history). So I set them but they don't seem to have any effect on even the 'normal' use of IDLE. The config files in .idlerc seem OK. Thoughts???

**Comment by pjritee** [comment]
On further investigation it looks like it's not storing the history so the arrow keys have nothing to work on - no idea what's going on

**Comment by sapi** [comment]
Not sure what's going on there.  It's being called directly as `idle3`, so it should work in the same manner as that.  I do alter the config file briefly before loading IDLE, but I reset it immediately afterwards.

**Comment by pjritee** [comment]
It's not your fault (at least I don't think so) - It happens if I call IDLE3 directly (and IDLE - which used to work)

**Comment by sapi** [comment]
As for the other issue, the idle interface is ludicrously convoluted (client/server model, with hidden dependencies and globals floating around).  I've spent an hour or two trying to hook in a proper reload function, but it doesn't want to work.  Part of the problem is that this kind of code injection is exactly what the client/server model was intended to protect *against*.

One route would be to look into subclassing some of the idlelib classes, but that's going to get very complex very quickly, given all the interdependencies.

**Comment by pjritee** [comment]
I think we need a KISS approach here - there are more important things to do. Maybe just the simplest approach - kill the interpreter when changing problems and then just choosing it again for a different problem. Maybe the same approach after an edit. Will that work?

**Comment by sapi** [comment]
I changed it so that the interpreter is killed each time the tests are run (which includes whenever the problem is changed).

Annoyingly, this puts it back in the background, but there's not much we can do about that without using the OS-specific libraries (which are not installed by default).

I'm half tempted to install them with pip automatically, but that's a tad rude...
